### ISSUE TITLE
Validation set results?

### ISSUE THREAD

**Issue by JonathonLuiten** [feiaxyt/Winner_ECCV20_TAO#1]
Hey!

Awesome job winning the TAO challenge @ ECCV20.

We would love to compare to your method (but using a different evaluation methodology) for our ICCV paper (deadline in 1.5 days).

In order to do that we would need the result of your method of the TAO validation set.

Do you just have this on your computer and you could easily share? It would be AWESOME if that's the case.

We need val because test gt is hidden so we can't run our different evaluation code on it. The test results for your method can be downloaded from MOTCha website but not val.

Thanks heaps,
Jono

**Comment by feiaxyt** [comment]
The result for the TAO validation set can be dowloaded in [TAO_val](https://drive.google.com/file/d/1NGLcQ40ci2MfbJK34hq37mv9iTOXV2sh/view?usp=sharing).

**Comment by JonathonLuiten** [comment]
Awesome thanks!!!

**Comment by Zhongdao** [comment]
Hi @feiaxyt!

Good work!

I'm currently working on a project that aims at solving multiple tracking tasks under a unified framework and would love to compare it with your method on TAO.

Would you mind uploading the results of your method on the TAO _**test**_ set also? It seems results cannot be downloaded from the MOTChallenge website now.

 Appreciate it if you could share the results!
