### ISSUE TITLE
How can I get train_img_list.txt?

### ISSUE THREAD

**Issue by shwoo1219** [feiaxyt/Winner_ECCV20_TAO#2]
Could you please provide the code snippet to convert the JSON file provided by the tao to get *.txt files?

**Comment by shwoo1219** [comment]
```
import json
import os

JSON_PATH = '/data1/tao/annotations/train.json' # modify with yours
with open(JSON_PATH) as f:
	data = json.load(f)

out_text_file = open("train_img_list.txt", "w")

n_frames = len(data['images'])
for n in range(n_frames):
	file_name = data['images'][n]['file_name']
	tmp = out_text_file.write(file_name + "\n")

out_text_file.close()
```

**Comment by yechenzhi** [comment]
> ```
> import json
> import os
> 
> JSON_PATH = '/data1/tao/annotations/train.json' # modify with yours
> with open(JSON_PATH) as f:
> 	data = json.load(f)
> 
> out_text_file = open("train_img_list.txt", "w")
> 
> n_frames = len(data['images'])
> for n in range(n_frames):
> 	file_name = data['images'][n]['file_name']
> 	tmp = out_text_file.write(file_name + "\n")
> 
> out_text_file.close()
> ```



> Could you please provide the code snippet to convert the JSON file provided by the tao to get *.txt files?

Do you get the train.json file from https://motchallenge.net/tao_download.php?
